version: '3'

services:
  app:
    depends_on:
      - postgres
    links:
      - postgres
    build: .
    env_file: ./.env
    ports:
      - "$SPRING_PORT:$SPRING_PORT"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgres:$DB_PORT/$DB_DATABASE",
        "spring.datasource.username" : "$DB_USER",
        "spring.datasource.password" : "$DB_PASS",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: "$DB_DATABASE"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASS"
      PGPASSWORD: admin
      TZ: "Asia/Tokyo"
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin: